//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatCurso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatCurso()
        {
            this.Cursos = new HashSet<Cursos>();
            this.CatCurso1 = new HashSet<CatCurso>();
        }
    
        public short id { get; set; }
        public string clave { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public Nullable<byte> horas { get; set; }
        public Nullable<short> idPrerequisito { get; set; }
        public Nullable<bool> activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cursos> Cursos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatCurso> CatCurso1 { get; set; }
        public virtual CatCurso CatCurso2 { get; set; }
    }
}
