//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CursosAlumnos
    {
        public int id { get; set; }
        public Nullable<short> idCurso { get; set; }
        public Nullable<int> idAlumno { get; set; }
        public Nullable<System.DateTime> fechaIncripcion { get; set; }
        public Nullable<System.DateTime> fechaBaja { get; set; }
        public Nullable<byte> calificacion { get; set; }
    
        public virtual Alumnos Alumnos { get; set; }
        public virtual Cursos Cursos { get; set; }
    }
}
